### PR TITLE
Added function to return the whole result of access_token and username

### PR DESCRIPTION
**Pull request by jasonngpt**
Added a function to return the whole result which contains the username and the access_token instead of just access_token. Also added some sample in the demo-server.rb to show the results.

### CODE REVIEW

**Comment by turadg** [comment]
Thanks for the contribution! I'm not using this lib anymore and it could use a new maintainer. Are you interested?

**Comment by srt32** [comment]
@turadg I'm new to this lib but am looking to do more work with pocket and would enjoy working on it. @jasonngpt, I'd be happy to share part of the load with you.

**Comment by jasonngpt** [comment]
thanks @turadg! I will be happy to take it up with @srt32 as I am using this lib for a new webapp I just started on.. [SpruceKit](www.sprucekit.com) do check it out! :) it is open-source too.. 

happy new year guys!

**Comment by turadg** [comment]
@jasonngpt I've added you as a collaborator so you should have push and issue management permissions now.

@srt32 I'd like to only add people after they contribute by PR.

**Comment by jasonngpt** [comment]
@turadg yup ok thanks!

**Pull request merged**
